import { access, readFile } from "node:fs/promises";
import { join } from "node:path";
import { expect, test } from "bun:test";
import { verifyDist } from "../scripts/verify-dist.js";

const root = process.cwd();

test("Given the canonical manifest, when package entry points are inspected, then Git consumers receive tracked source, dist, types, and an executable bin", async () => {
  const manifest = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as {
    readonly bin: Readonly<Record<string, string>>;
    readonly exports: { readonly ".": Readonly<Record<string, string>> };
    readonly files: readonly string[];
    readonly repository: { readonly type: string; readonly url: string };
    readonly scripts: Readonly<Record<string, string>>;
  };

  expect(manifest.exports["."].bun).toBe("./src/index.ts");
  expect(manifest.exports["."].import).toBe("./dist/index.js");
  expect(manifest.exports["."].types).toBe("./dist/index.d.ts");
  expect(manifest.bin["ai-auth-kit"]).toBe("./dist/cli.js");
  expect(manifest.files).toEqual([
    "dist",
    "src/account-oauth-browser.ts",
    "src/account-oauth-github.ts",
    "src/account-oauth-openai.ts",
    "src/account-oauth-shared.ts",
    "src/account-oauth.ts",
    "src/atomic-file.ts",
    "src/auth-policy-registry.ts",
    "src/catalog-adapter.ts",
    "src/catalog-cache.ts",
    "src/catalog-http.ts",
    "src/catalog-normalize.ts",
    "src/catalog-refresh.ts",
    "src/catalog-runtime.ts",
    "src/catalog-snapshot.ts",
    "src/catalog-source-schema.ts",
    "src/catalog.ts",
    "src/cli.ts",
    "src/cliproxyapi-archive.ts",
    "src/cliproxyapi-cache.ts",
    "src/cliproxyapi-http.ts",
    "src/cliproxyapi-release.ts",
    "src/cliproxyapi.ts",
    "src/credential-removal.ts",
    "src/external-auth.ts",
    "src/index.ts",
    "src/kit-runtime-auth.ts",
    "src/kit.ts",
    "src/picker.ts",
    "src/safe-dir.ts",
    "src/schema.ts",
    "src/storage.ts",
    "src/types.ts",
    "generated/catalog-provenance.json",
    "generated/catalog-snapshot.json",
    "README.md",
    "LICENSE",
    "package.json",
  ]);
  expect(manifest.repository).toEqual({ type: "git", url: "https://github.com/abran-labs/ai-auth-kit.git" });
  for (const lifecycle of ["prepare", "prepack", "postinstall", "preinstall", "install"]) {
    expect(manifest.scripts[lifecycle]).toBeUndefined();
  }
  await access(join(root, "dist", "index.js"));
  await access(join(root, "dist", "index.d.ts"));
  await access(join(root, "dist", "index.js.map"));
  await access(join(root, "dist", "cli.js"));
  const ignored = Bun.spawn({ cmd: ["git", "check-ignore", "dist/index.js"], cwd: root, stdout: "pipe", stderr: "pipe" });
  expect(await ignored.exited, `${await new Response(ignored.stdout).text()}${await new Response(ignored.stderr).text()}`).toBe(1);
});

test("Given generated distribution files, when their maps are inspected, then they are portable and deterministic", async () => {
  const map = await readFile(join(root, "dist", "index.js.map"), "utf8");
  expect(map).not.toContain(root);
  expect(map).not.toMatch(/20\d{2}-\d{2}-\d{2}T/);
});

test("Given tracked distribution files, when source is rebuilt in a temporary directory, then every generated byte remains fresh", async () => {
  const result = await verifyDist(root);
  expect(result.files).toBeGreaterThan(0);
}, 20_000);

test("Given immutable-consumer documentation, when its dependency grammar is inspected, then it pins the reviewed public source commit", async () => {
  const readme = await readFile(join(root, "README.md"), "utf8");
  expect(readme).toContain("github:abran-labs/ai-auth-kit#adcb364fa086ec1a854d2b412a5efbd530595b98");
  expect(readme).not.toContain("github:abran-labs/ai-auth-kit#main");
  expect(readme).toMatch(/(?:isn't|not) published to npm or GitHub Packages/);
  expect(readme).not.toContain('"@abran-labs/ai-auth-kit": "github:abran-labs/ai-auth-kit#master"');
  expect(readme).not.toContain("npm install @abran-labs/ai-auth-kit");
});
