#!/bin/sh
set -eu

: "${RELEASE_TARBALL:?RELEASE_TARBALL is required}"
: "${RELEASE_TARBALL_SHA256:?RELEASE_TARBALL_SHA256 is required}"
: "${RELEASE_TARBALL_SRI:?RELEASE_TARBALL_SRI is required}"
: "${RELEASE_TARBALL_FILENAME:?RELEASE_TARBALL_FILENAME is required}"
: "${RELEASE_TARBALL_INVENTORY:?RELEASE_TARBALL_INVENTORY is required}"
: "${RELEASE_SOURCE_TAG_SHA:?RELEASE_SOURCE_TAG_SHA is required}"
export RELEASE_TARBALL RELEASE_TARBALL_FILENAME RELEASE_TARBALL_SHA256 RELEASE_TARBALL_SRI RELEASE_TARBALL_INVENTORY RELEASE_SOURCE_TAG_SHA
exec sh scripts/npm-preflight.sh
